services:
  - type: web
    name: craftman-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    plans:
      - name: free
        cpu: 0.25
        memory: 512MB
        price: 0
